---
on:
  push:

jobs:
  norminette-check:
    runs-on: ubuntu-latest
    name: "Norminette"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Norminette via Docker
        run: |
          docker run --rm \
            -v $(pwd):/root/src \
            42lambdas/norminette:latest \
            -RCheckForbiddenSourceHeader