---
on:
  push:

jobs:
  norminette-check:
    runs-on: ubuntu-latest
    name: "Vérification avec Norminette (Depuis 42school/norminette)"

    steps:
      - name: Checkout code utilisateur
        uses: actions/checkout@v3

      - name: Checkout dépôt officiel Norminette
        uses: actions/checkout@v3
        with:
          repository: 42school/norminette
          path: norminette

      - name: Installer Python et dépendances
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installer les dépendances requises
        run: |
          cd norminette
          pip install -r requirements.txt || true

      - name: Exécuter la norminette sur le code utilisateur
        run: |
          cd norminette
          python __main__.py ../ -RCheckForbiddenSourceHeader