---
on:
  push:

jobs:
  norminette-check:
    runs-on: ubuntu-latest
    name: "Norminette Check"

    steps:
      - name: Checkout user code
        uses: actions/checkout@v3

      - name: Install Python3
        uses: actions/setup-python@v4
        with:
            python-version: "3.10"

      - name: Install Norminette using pip
        run: |
            python3 -m pip install --upgrade pip setuptools
            python3 -m pip install norminette

      - name: Execute Norminette
        run: |
            norminette -RCheckForbiddenSourceHeader